changed the package path for Settings
SambhaviPD/RecipeBuddy pull request #62
Opened 2023-05-29 10:14 UTC by SambhaviPD

2023-05-30 09:24 UTC, Zaubeerer commented
Hey @SambhaviPD, were you able to solve the remaining import errors?

2023-05-30 10:15 UTC, SambhaviPD commented
Well, I moved the tests to backend and frontend folder and just kept appropriate test files on them. I did this because I got the same error as earlier. Since moving this will keep things at the same level, I tried this approach. At the moment, it fails with the following:

![image](https://github.com/SambhaviPD/RecipeBuddy/assets/25765169/bdf0c0e0-48fe-428e-944d-1e7e7cb1ccfd)


Will continue to look at it.

2023-05-30 10:18 UTC, Zaubeerer commented
So the docker compose works now and the only problem remaining is with the tests?}

2023-05-30 10:48 UTC, SambhaviPD commented
@Zaubeerer - Made some progress. Now tests related to backend goes through. Mistake was I did not give an explicit `cd recipebuddy/backend` before the command `pytest tests`. 

So it was searching for tests folder in the root directory. This one is fixed now.

Now testcases related to frontend fail due to the fixture `page` not available. Just checking that one.

2023-05-30 12:04 UTC, SambhaviPD commented
@Zaubeerer  - That's also fixed. I had to install few more packages for playwright and pytest to work together.

I'm in the last step now. Playwright testcases that invoke the backend fails. The name we gave in docker_compose is `backend` as service name, that's what I use when I construct the API_URL. 

Ring a bell?

2023-05-30 17:10 UTC, Zaubeerer requested changes
Hey @SambhaviPD, happy that you were able to resolve the errors!

I have a minor requirement, since you should not need to import from `src`, if the package is properly installed.

Otherwise, looks good 👍

2023-05-30 17:10 UTC, Zaubeerer commented on .github/workflows/build_and_test.yml
> +    - name: Run tests
You may want to rename this to `Run backend tests`

2023-05-30 17:10 UTC, Zaubeerer commented on .github/workflows/build_and_test.yml
>      - name: Run tests
```suggestion
    - name: Run frontend tests

```

2023-05-30 17:10 UTC, Zaubeerer commented on recipebuddy/backend/src/recipebuddy_backend/main.py
> +from src.recipebuddy_backend.configuration import Settings
`src` should NOT be required, if the `recipebuddy_backend` package is properly installed (`pip install -e .`)

2023-05-31 06:27 UTC, SambhaviPD commented on .github/workflows/build_and_test.yml
> +    - name: Run tests
renamed as suggested

2023-05-31 06:27 UTC, SambhaviPD commented on .github/workflows/build_and_test.yml
>      - name: Run tests
renamed as suggested

2023-05-31 06:29 UTC, SambhaviPD commented on recipebuddy/frontend/requirements.txt
> +pytest-playwright==0.3.3
I now have frontend related packages under frontend/requirements.txt. Likewise, for backend. Is that good enough?

2023-05-31 06:34 UTC, SambhaviPD commented on recipebuddy/backend/requirements.txt
> +pytest==7.3.1
Could you please elaborate this one a bit @Zaubeerer ?

2023-05-31 07:08 UTC, Zaubeerer commented on recipebuddy/frontend/requirements.txt
> +pytest-playwright==0.3.3
Yes, for now it is good enough. 👍 

Later, you may want to separate the requirements as suggested in https://github.com/SambhaviPD/RecipeBuddy/pull/62#discussion_r1211152541

2023-05-31 07:10 UTC, Zaubeerer commented on recipebuddy/backend/requirements.txt
> +pytest==7.3.1
See the following discussion: https://chat.openai.com/share/031e278a-947a-4419-9937-adf1be20511c

2023-05-31 07:33 UTC, SambhaviPD commented on recipebuddy/backend/tests/test_main.py
> +from src.recipebuddy_backend.main import app
If I remove src, again docker-compose up fails with ModuleNotFoundError.

For test_main.app. I moved tests folder under src and changed the import accordingly. I did not commit it, so not sure whether CI will go through.

2023-05-31 08:27 UTC, SambhaviPD commented on recipebuddy/backend/tests/test_main.py
> +from src.recipebuddy_backend.main import app
Ok, let me try fixing it then

2023-05-31 08:28 UTC, Zaubeerer commented on recipebuddy/backend/tests/test_main.py
> +from src.recipebuddy_backend.main import app
I just checked your GitHub actions configuration and you need to `pip install .` both backend and frontend so that the tests can be imported from the packages in the CICD ;-) 

If it doesn't work, try `pip install -e .`.

However, this should not be a problem in the docker-compose up command, since in the Dockerfile the packages are installed.

Can you share error messages?

2023-05-31 11:55 UTC, SambhaviPD commented on recipebuddy/backend/tests/test_main.py
> +from src.recipebuddy_backend.main import app
@Zaubeerer - I removed src from imports. Infact, right now it's just `from .configuration import Settings`

Both docker-compose up as well as github workflow CI go through.

2023-05-31 12:28 UTC, SambhaviPD commented on recipebuddy/backend/src/recipebuddy_backend/main.py
> +from src.recipebuddy_backend.configuration import Settings
Fixed

2023-05-31 12:36 UTC, Zaubeerer reviewed
Hey @SambhaviPD, we are getting there 💪 

I am not yet able to fully approve, but would not request changes either.

Feel free to merge, we can always improve it later 🙏

2023-05-31 12:36 UTC, Zaubeerer commented on recipebuddy/backend/src/recipebuddy_backend/main.py
> +from .configuration import Settings
this does not seem right 🤔 

@bbelderbos, what is your take on this?

2023-05-31 12:36 UTC, Zaubeerer commented on recipebuddy/backend/src/recipebuddy_backend/main.py
> +from .configuration import Settings
```suggestion
from recipebuddy_backend.configuration import Settings

```

2023-05-31 12:36 UTC, Zaubeerer commented on recipebuddy/backend/setup.py
> +    packages=['src.recipebuddy_backend'],
Not sure about this one, does it make a difference?

2023-05-31 13:32 UTC, SambhaviPD commented on recipebuddy/backend/src/recipebuddy_backend/main.py
> +from .configuration import Settings
If I give `from recipebuddy_backend.configuration import Settings`, it throws an error. Also, `from .configuration import Settings` seems logically correct as configuration.py and main.py are at the same level.

2023-05-31 13:34 UTC, SambhaviPD commented
@Zaubeerer - I'm unable to merge as it shows as Changes requested. I requested for a re-review.

2023-05-31 14:48 UTC, bbelderbos commented on recipebuddy/backend/src/recipebuddy_backend/main.py
> +from .configuration import Settings
Yep was gonna say, if both modules are in the same directory or package, then it should be ok to do a relative import like this.

2023-06-02 09:45 UTC, Zaubeerer approved these changes
LGTM!

2023-06-04 08:48 UTC, merged